// This work is licensed under a Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/
// © LuxAlgo

//@version=5
indicator('Smart Money Concepts [LuxAlgo]', 'LuxAlgo - Smart Money Concepts', overlay = true, max_labels_count = 500, max_lines_count = 500, max_boxes_count = 500)

// IMPORT THE LIBRARY
// NOTE: You MUST publish SMCLibrary.pine first!
// Replace 'User/SMCLibrary/1' with your actual published library name/version.
import User/SMCLibrary/1 as SMC

//---------------------------------------------------------------------------------------------------------------------
// SETTINGS (Inputs)
//---------------------------------------------------------------------------------------------------------------------
insideColor = input.color(color.new(color.blue, 0), "Inside Candle Color")
isInside = high < high[1] and low > low[1]
barcolor(isInside ? insideColor : na)

// Visual & Logic Settings
modeInput = input.string('Historical', 'Mode', group = 'Smart Money Concepts', options = ['Historical', 'Present'])
styleInput = input.string('Colored', 'Style', group = 'Smart Money Concepts', options = ['Colored', 'Monochrome'])
showTrendInput = input(false, 'Color Candles', group = 'Smart Money Concepts')

// Internals
showInternalsInput = input(true, 'Show Internal Structure', group = 'Real Time Internal Structure')
showInternalBullInput = input.string('All', 'Bullish Structure', group = 'Real Time Internal Structure', options = ['All', 'BOS', 'CHoCH'])
internalBullColorInput = input(#089981, '', group = 'Real Time Internal Structure')
showInternalBearInput = input.string('All', 'Bearish Structure', group = 'Real Time Internal Structure', options = ['All', 'BOS', 'CHoCH'])
internalBearColorInput = input(#F23645, '', group = 'Real Time Internal Structure')
internalFilterConfluenceInput = input(false, 'Confluence Filter', group = 'Real Time Internal Structure')
internalStructureSize = input.string(size.tiny, 'Internal Label Size', group = 'Real Time Internal Structure', options = [size.tiny, size.small, size.normal])

// Swings
showStructureInput = input(true, 'Show Swing Structure', group = 'Real Time Swing Structure')
showSwingBullInput = input.string('All', 'Bullish Structure', group = 'Real Time Swing Structure', options = ['All', 'BOS', 'CHoCH'])
swingBullColorInput = input(#089981, '', group = 'Real Time Swing Structure')
showSwingBearInput = input.string('All', 'Bearish Structure', group = 'Real Time Swing Structure', options = ['All', 'BOS', 'CHoCH'])
swingBearColorInput = input(#F23645, '', group = 'Real Time Swing Structure')
swingStructureSize = input.string(size.small, 'Swing Label Size', group = 'Real Time Swing Structure', options = [size.tiny, size.small, size.normal])
showSwingsInput = input(false, 'Show Swings Points', group = 'Real Time Swing Structure')
swingsLengthInput = input.int(50, '', group = 'Real Time Swing Structure', minval = 10)
showHighLowSwingsInput = input(true, 'Show Strong/Weak High/Low', group = 'Real Time Swing Structure')

// Order Blocks
showInternalOrderBlocksInput = input(true, 'Internal Order Blocks', group = 'Order Blocks')
internalOrderBlocksSizeInput = input.int(5, '', group = 'Order Blocks', minval = 1, maxval = 20)
showSwingOrderBlocksInput = input(false, 'Swing Order Blocks', group = 'Order Blocks')
swingOrderBlocksSizeInput = input.int(5, '', group = 'Order Blocks', minval = 1, maxval = 20)
orderBlockFilterInput = input.string('Atr', 'Order Block Filter', group = 'Order Blocks', options = ['Atr', 'Cumulative Mean Range'])
orderBlockMitigationInput = input.string('High/Low', 'Order Block Mitigation', group = 'Order Blocks', options = ['Close', 'High/Low'])
internalBullishOrderBlockColor = input.color(color.new(#3179f5, 80), 'Internal Bullish OB', group = 'Order Blocks')
internalBearishOrderBlockColor = input.color(color.new(#f77c80, 80), 'Internal Bearish OB', group = 'Order Blocks')
swingBullishOrderBlockColor = input.color(color.new(#1848cc, 80), 'Bullish OB', group = 'Order Blocks')
swingBearishOrderBlockColor = input.color(color.new(#b22833, 80), 'Bearish OB', group = 'Order Blocks')

// Equal Highs/Lows
showEqualHighsLowsInput = input(true, 'Equal High/Low', group = 'EQH/EQL')
equalHighsLowsLengthInput = input.int(3, 'Bars Confirmation', group = 'EQH/EQL', minval = 1)
equalHighsLowsThresholdInput = input.float(0.1, 'Threshold', group = 'EQH/EQL', minval = 0, maxval = 0.5, step = 0.1)
equalHighsLowsSizeInput = input.string(size.tiny, 'Label Size', group = 'EQH/EQL', options = [size.tiny, size.small, size.normal])

// Fair Value Gaps
showFairValueGapsInput = input(false, 'Fair Value Gaps', group = 'Fair Value Gaps')
fairValueGapsThresholdInput = input(true, 'Auto Threshold', group = 'Fair Value Gaps')
fairValueGapsTimeframeInput = input.timeframe('', 'Timeframe', group = 'Fair Value Gaps')
fairValueGapsBullColorInput = input.color(color.new(#00ff68, 70), 'Bullish FVG', group = 'Fair Value Gaps')
fairValueGapsBearColorInput = input.color(color.new(#ff0008, 70), 'Bearish FVG', group = 'Fair Value Gaps')
fairValueGapsExtendInput = input.int(1, 'Extend FVG', group = 'Fair Value Gaps', minval = 0)

// Helper: Populate Settings Object
settings = SMC.Settings.new(
    swingBullColorInput, swingBearColorInput, fairValueGapsBullColorInput, fairValueGapsBearColorInput, 
    color.gray, color.gray, // placeholder for zones, irrelevant for this demo
    internalBullishOrderBlockColor, internalBearishOrderBlockColor, swingBullishOrderBlockColor, swingBearishOrderBlockColor,
    showSwingsInput, showStructureInput, showInternalsInput, showTrendInput, showHighLowSwingsInput, false, 
    showEqualHighsLowsInput, showFairValueGapsInput, showInternalOrderBlocksInput, showSwingOrderBlocksInput,
    equalHighsLowsThresholdInput, equalHighsLowsSizeInput, modeInput,
    internalStructureSize, swingStructureSize,
    internalFilterConfluenceInput, showInternalBullInput, showInternalBearInput, showSwingBullInput, showSwingBearInput,
    internalOrderBlocksSizeInput, swingOrderBlocksSizeInput, orderBlockMitigationInput,
    fairValueGapsExtendInput, fairValueGapsThresholdInput, fairValueGapsTimeframeInput
)

//---------------------------------------------------------------------------------------------------------------------
// STATE VARIABLES
//---------------------------------------------------------------------------------------------------------------------
var pivot swingHigh = SMC.Pivot.new(na, na, false)
var pivot swingLow = SMC.Pivot.new(na, na, false)
var pivot internalHigh = SMC.Pivot.new(na, na, false)
var pivot internalLow = SMC.Pivot.new(na, na, false)
var pivot equalHigh = SMC.Pivot.new(na, na, false)
var pivot equalLow = SMC.Pivot.new(na, na, false)

var trend swingTrend = SMC.Trend.new(0)
var trend internalTrend = SMC.Trend.new(0)

var equalDisplay equalHighDisplay = SMC.EqualDisplay.new()
var equalDisplay equalLowDisplay = SMC.EqualDisplay.new()

var trailingExtremes trailing = SMC.TrailingExtremes.new()
SMC.Alerts currentAlerts = SMC.Alerts.new()

var array<SMC.OrderBlock> swingOrderBlocks = array.new<SMC.OrderBlock>()
var array<SMC.OrderBlock> internalOrderBlocks = array.new<SMC.OrderBlock>()
var array<float> parsedHighs = array.new<float>()
var array<float> parsedLows = array.new<float>()
var array<int> times = array.new<int>()

//---------------------------------------------------------------------------------------------------------------------
// EXECUTION
//---------------------------------------------------------------------------------------------------------------------

// Calculate Volatility (ATR)
atrMeasure = ta.atr(200)

// Store Data
parsedHighs.push(high)
parsedLows.push(low)
times.push(time)

// Run Logic via Library
SMC.getCurrentStructure(swingsLengthInput, false, false, settings, currentAlerts, trailing, internalLow, internalHigh, swingLow, swingHigh, equalLow, equalHigh, atrMeasure, equalLowDisplay, equalHighDisplay)
SMC.getCurrentStructure(5, false, true, settings, currentAlerts, trailing, internalLow, internalHigh, swingLow, swingHigh, equalLow, equalHigh, atrMeasure, equalLowDisplay, equalHighDisplay)

if showEqualHighsLowsInput
    SMC.getCurrentStructure(equalHighsLowsLengthInput, true, false, settings, currentAlerts, trailing, internalLow, internalHigh, swingLow, swingHigh, equalLow, equalHigh, atrMeasure, equalLowDisplay, equalHighDisplay)

if showInternalsInput or showInternalOrderBlocksInput or showTrendInput
    SMC.displayStructure(true, settings, currentAlerts, internalHigh, swingHigh, internalLow, swingLow, internalTrend, swingTrend, internalOrderBlocks, swingOrderBlocks, parsedHighs, parsedLows, times)

if showStructureInput or showSwingOrderBlocksInput or showHighLowSwingsInput
    SMC.displayStructure(false, settings, currentAlerts, internalHigh, swingHigh, internalLow, swingLow, internalTrend, swingTrend, internalOrderBlocks, swingOrderBlocks, parsedHighs, parsedLows, times)

// Alerts
alertcondition(currentAlerts.swingBullishBOS, 'Bullish BOS', 'Bullish BOS')
// ... (Add other alerts as needed)
