# Fyers API Credentials
CLIENT_ID = "IYC0LYVD1I-100"
ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIl0sImF0X2hhc2giOiJnQUFBQUFCcGtCa2RZOUJ4cDdNMkJaNzBmSkZBYUthM1FYb3N4WGMyY0toS2syaFlQMGRRTFI4Y1JOUGp0d1RXUmlLWUpRS1B0NlRJVHJyVGhHeXNHV2c1czRySC14MHhqWlFWcGNFd0ZJckZjcFRCQzNtUnY1OD0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiIyMTgwM2U0ZDVlYzYyOGNhZGFiNWY0NTM3ODkwOGFmODBmOWEyNzFlMGMzNzlhYWEzZGJmYjgzNiIsImlzRGRwaUVuYWJsZWQiOiJZIiwiaXNNdGZFbmFibGVkIjoiWSIsImZ5X2lkIjoiWEQxMTI3MyIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzcxMTE1NDAwLCJpYXQiOjE3NzEwNTEyOTMsImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc3MTA1MTI5Mywic3ViIjoiYWNjZXNzX3Rva2VuIn0.ZbKPzqL-w4vwNwUs__cJVqRTghSEv_f_z9VRBr6kiTM"
SECRET_KEY = "F3BM968B6S"
REDIRECT_URL = "https://www.google.com"


# https://www.google.com/?s=ok&code=200&auth_code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOiJJWUMwTFlWRDFJIiwidXVpZCI6ImI5NDU2ZmU3YmIyZjQxZGU4NzZhZDVmMDY2ZDQ1ZDllIiwiaXBBZGRyIjoiIiwibm9uY2UiOiIiLCJzY29wZSI6IiIsImRpc3BsYXlfbmFtZSI6IlhEMTEyNzMiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiIyMTgwM2U0ZDVlYzYyOGNhZGFiNWY0NTM3ODkwOGFmODBmOWEyNzFlMGMzNzlhYWEzZGJmYjgzNiIsImlzRGRwaUVuYWJsZWQiOiJZIiwiaXNNdGZFbmFibGVkIjoiWSIsImF1ZCI6IltcImQ6MVwiLFwiZDoyXCIsXCJ4OjBcIixcIng6MVwiXSIsImV4cCI6MTc3MTA4MDMxOSwiaWF0IjoxNzcxMDUwMzE5LCJpc3MiOiJhcGkubG9naW4uZnllcnMuaW4iLCJuYmYiOjE3NzEwNTAzMTksInN1YiI6ImF1dGhfY29kZSJ9.gfZ6p5KE97_LVf8ai7LaP1GTcXEs9Q4YBx8w5ZbxUI0&state=None

# Strategy Parameters
TIMEFRAME = "D"  # Daily timeframe
ADX_PERIOD = 14
ADX_THRESHOLD = 25
RSI_PERIOD = 14
RSI_THRESHOLD = 50

# Exit Parameters
SL_PCT = 0.10  # 10% Stop Loss
TP_PCT = 0.10  # 10% Target Profit

# Nifty 50 Stocks (NSE Symbols)
NIFTY_50_SYMBOLS = [
    "NSE:ADANIENT-EQ", "NSE:ADANIPORTS-EQ", "NSE:APOLLOHOSP-EQ", "NSE:ASIANPAINT-EQ", "NSE:AXISBANK-EQ",
    "NSE:BAJAJ-AUTO-EQ", "NSE:BAJFINANCE-EQ", "NSE:BAJAJFINSV-EQ", "NSE:BPCL-EQ", "NSE:BHARTIARTL-EQ",
    "NSE:BRITANNIA-EQ", "NSE:CIPLA-EQ", "NSE:COALINDIA-EQ", "NSE:DIVISLAB-EQ", "NSE:DRREDDY-EQ",
    "NSE:EICHERMOT-EQ", "NSE:GRASIM-EQ", "NSE:HCLTECH-EQ", "NSE:HDFCBANK-EQ", "NSE:HDFCLIFE-EQ",
    "NSE:HEROMOTOCO-EQ", "NSE:HINDALCO-EQ", "NSE:HINDUNILVR-EQ", "NSE:ICICIBANK-EQ", "NSE:ITC-EQ",
    "NSE:INDUSINDBK-EQ", "NSE:INFY-EQ", "NSE:JSWSTEEL-EQ", "NSE:KOTAKBANK-EQ", "NSE:LTIM-EQ",
    "NSE:LT-EQ", "NSE:M&M-EQ", "NSE:MARUTI-EQ", "NSE:NTPC-EQ", "NSE:NESTLEIND-EQ",
    "NSE:ONGC-EQ", "NSE:POWERGRID-EQ", "NSE:RELIANCE-EQ", "NSE:SBILIFE-EQ", "NSE:SBIN-EQ",
    "NSE:SUNPHARMA-EQ", "NSE:TCS-EQ", "NSE:TATACONSUM-EQ", "NSE:TATAMOTORS-EQ", "NSE:TATASTEEL-EQ",
    "NSE:TECHM-EQ", "NSE:TITAN-EQ", "NSE:ULTRACEMCO-EQ", "NSE:UPL-EQ", "NSE:WIPRO-EQ"
]
